### ISSUE TITLE
[Question] can input() and confirm() be tested?

### ISSUE THREAD

**Issue by kristijanhusak** [junegunn/vader.vim#200]
Hi,

is there a way to test `input()` and `confirm()` somehow?

For example:
```vimL
function! Myquestion() abort
let l:input = input('What is your name?', '')
call setline(1, 'Your name is '.l:input)
endfunction

nnoremap Y :call Myquestion()<CR> 
```

My test looks like this:

```vader
Given (Text):
  Hello

Do:
  Y
  John\<CR>

Expect:
  Your name is John

```

but the `input()` stops the test. How can i enter something to input or choose an option from `confirm()`, if there is a way?

**Comment by SidOfc** [comment]
Hello @kristijanhusak!

I'm actually interested in this, I do have `input()` working for me though. `confirm()` is the only one that fails. Since you closed this, I'm curious wether you found a solution to getting `confirm()` to work and if so, are willing to share your solution :)

As for the `input()`, did you try putting everything on the same line? My plugin uses a mapping `c` to create files and directories (directory explorer plugin), this is my working test:

```vader
Expect (buffer shows contents nested in test/files/nested/directory/):
  files/
    folded-exe/example.sh
    folded-sym/example.ln
    folded-sym-exe/example.sh
    folded-sym-long/example.ln
  - nested/directory/
      a.txt
      b.txt
    example.ln
    example.sh
    example.txt

Do (add nested/directory/c.txt):
  c/nested/directory/c.txt\<Cr>

Expect (the file to be created):
  files/
    folded-exe/example.sh
    folded-sym/example.ln
    folded-sym-exe/example.sh
    folded-sym-long/example.ln
  - nested/directory/
      a.txt
      b.txt
      c.txt
    example.ln
    example.sh
    example.txt
```

Hope it helps you, or anyone else out there for that matter!

**Comment by kristijanhusak** [comment]
Hi @SidOfc,

I gave up doing tests with it in vader, but I managed to to do it in vim-themis by creating a function around `input`, and mocking it in tests. Something like this:

```vimL
"autoload/my_plugin.vim
function! my_plugin#input(text, default) abort
  return input(a:text, a:default)
endfunction

function! my_plugin#run() abort
  let name = my_plugin#input('Enter name:', '')
  return name
endfunction
```

```vimL
test.vim

runtime! autoload/my_plugin.vim
function! my_plugin#input(text, default) abort
  if a:text ==? 'Enter name:'
    return 'Test name'
  endif
endfunction

let test_name = call my_plugin#run()
assert_equals(test_name, 'Test name')
```

I haven't tried it in Vader, but i assume it would work.

**Comment by SidOfc** [comment]
Thanks for the response and sharing your method :+1: 

I think I'll try this with Vader. I'm already wrapping Vim's native `confirm()` in a `s:` local function, might as well make it a `myplugin#confirm()` and see if I can stub it in the tests!

I'll report back if successful :crossed_fingers:

**Comment by SidOfc** [comment]
I got some errors with regards to overwriting `myplugin#confirm()` in a file that didn't match the name so unfortunately I could not go for it. Setting up another testing environment "just" to test confirms seemed overkill, so I decided to put a minimal amount of "test boilerplate" in the plugin code itself:

```viml
" prefer a script-local namespace to make it clear these are test-utils
let s:test = {}

function! s:test.vader_confirmed() abort
  return get(g:, '__myplugin_vader_confirm_reply__', '') != ''
endfunction

function! s:test.vader_confirm_answer() abort
  let answer = g:__myplugin_vader_confirm_reply__
  unlet g:__myplugin_vader_confirm_reply__
  return answer
endfunction
```

Then in my actual `s:util.confirm()` function, I changed it to first check `s:test.vader_confirmed()`:

```viml
function! s:util.confirm(overrides) abort
  if s:test.vader_confirmed()
    return s:test.vader_confirm_answer()
  endif

  " ... rest of function code ...
endfunction
```

Then, when I want to use it in some .vader file, all I need to do is **manually set the coice** like so:

```vader
Execute (some setup before actual test involving Vim's confirm function):
  let g:__myplugin_vader_confirm_reply__ = 2
```

While I don't think it's pretty, it also doesn't really matter for performance. The helper can also be extended to store the parameters you can pass to a confirm (like `overrides` in my case) so that you can check if you got the right confirm to show up if needed.

So my 2cents: It's up to whoever reads this to decide wether to implement the above or use something like `themis` instead. Personally I like Vader and it serves me well in most other cases, so working around this with ~5-25 lines of boilerplate is fine for me.

For reference, this is a permalink to the test-file using it: https://github.com/SidOfc/treevial/blob/ce36d34af120a853303fe1ff600cfb6e11b7280c/test/main.vader
