### ISSUE TITLE
Enable range and filename at the same time

### ISSUE THREAD

**Issue by janko-m** [junegunn/vader.vim#51]
I recently created [vim-test](https://github.com/janko-m/vim-test), which is a plugin for running any kind of tests. Since I finally reazlied why Vader.vim is so awesome, I want to add support for it to vim-test.

One feature that test.vim has is that you can run the last test without having to switch to that test file. It supports nearest, file and suite tests. So, in the implementation, when user runs the last nearest test, I ideally want to run

```
:<line1>,<line2>Vader <file>
```

However, that's not currently possible. Is it possible to implement it?

**Comment by junegunn** [comment]
As you might have noticed, it's currently prohibited, since I thought it could be confusing as `:Vader` can take multiple files as the argument. It's probably okay to allow it when only a single file is specified. But still it feels really unnatural for `:Vader` command to take range from one file and apply it on another file.

So I'd still like to disallow such usage with `:Vader` command but I can allow it with `vader#run()` function.

**Comment by janko-m** [comment]
I tend to think in a way that "range" is just a pair of line numbers, which don't belong to any file. We can use visual markers of visually selected lines in the current file, but that's just one way of passing them in, and they still get translated to numbers (do they?).

But of course, I will be more than satisfied using `vader#run()` directly.

**Comment by junegunn** [comment]
Well, maybe it's just me but I almost never manually type in range to command or function call, except for `%s`. Anyway check out the above commit.

**Comment by janko-m** [comment]
Awesome, thanks, I managed to implement it now!
