### ISSUE TITLE
Mocking

### ISSUE THREAD

**Issue by wikimatze** [junegunn/vader.vim#58]
Hello,

I'm testing my first plugin and I'm wondering how I can test the following piece of code:

```vim
if !executable('banshee')
  echoerr "banshee is not installed!"
  finish
endif
```

How can I mock the `executable()`?

Bests

Matthias

**Comment by junegunn** [comment]
I don't think it's possible in vimscript.

**Comment by wikimatze** [comment]
Thanks for your answer!

**Comment by fatso83** [comment]
Related discussion for those interested: https://vi.stackexchange.com/questions/29350/unit-testing-vimscript-built-ins-possible-to-override-mock-or-inject-substitute

**Comment by fatso83** [comment]
@wikimatze Since this tickled my curious side I ended up creating a proof-of-concept on https://github.com/fatso83/coc.nvim/commit/6d7d0d3461dad2bc03a757ad4654e94d07b0f97a#diff-65372dd7a2f98d044351ab1b251062e41cdcbf6ae3386e3904548bc397a479faR9-R20. In essence, VimScript does not allow you to overwrite built-ins, but, like you would in C, you can make use of a pre-processing stage that substitutes calls to the built-ins with calls to mock implementations and then run your test on _that_. The POC does this: not super elegantly, but then again, it's a POC :neckbeard: 

Seeing that it worked actually made me think about doing it "properly" by implementing a VimScript parser in Node that could produce an AST, which again could be used for auto-creating mock implementations, various support constructs (like `GetCallCount("has")`, `GetCallArgument("has",2,1)`, etc), but I don't really have an itch to scratch, so I'll pass it on 😸

**Comment by wikimatze** [comment]
@fatso83 wow, even after all tose years, it's somehow still relevant. Sometimes it's okay to not have 100% test coverage. And as you said, it's a POC.

**Comment by codeinabox** [comment]
What if I wanted to mock a shell command? I've created the following custom Bash env 

```sh
#!/bin/bash

cargo() {
    cat mock-manifest.json
}
```

And then added `let $BASH_ENV = ".vim_bash_env"` to the `before` block in my tests. However on running the tests I get the following error:

> # Vim(let):E491: JSON decode error at '/usr/local/bin/bash: line 1: cargo: command not found

**Comment by fatso83** [comment]
@codeinabox You need to add more context to have this reproducible. If I open up a vim session and type 
```
: let $BASH_ENV = "$PWD/.vim_bash_env" 
: !bash -c "yoyo 123"
```

while .vim_bash_env has this content:
```
yoyo(){
       echo YOYO  $1
 }
```

it produces "YOYO 123", as expected. Just create a minimal git repo to reproduce

**Comment by codeinabox** [comment]
I am glad you asked, I actually have a pull request that has tests that aren't passing: https://github.com/vim-test/vim-test/pull/646

I followed the same process as above but when I run the tests I get this error: 

```
spec/cargotest_spec.vim ..................... 1/? 
not ok 1 - Cargo runs file tests
# {example}..test#run[19]..test#base#build_position[1]..test#rust#cargotest#build_position[5]..<SNR>85_test_namespace, line 17
# Vim(let):E491: JSON decode error at '/usr/local/bin/bash: line 1: cargo: command not found
# '
# -----------------------------------------------------------------------------
# {vspec}[6]..<SNR>2_run_suites[6]..13[4]..14, line 2
# Vim(cd):E344: Cannot find directory "spec/fixtures/cargo/crate" in cdpath
Bailout called.  Further testing stopped:  Unexpected error happened while processing a test script.
spec/cargotest_spec.vim ..................... Failed 1/1 subtests 
```

**Comment by fatso83** [comment]
@codeinabox The issues you encounter are at least not Vi specific, but Travis/environment specific. I suggest digging into this with the usual toolbelt:
- figure out what `$PWD` is (obviously not the one you hoped it would be)
- replace `/bin/bash` with something that prints out more debugging info (like `/usr/bin/env bash -o xtrace`)

The two errors above are:
1. Cannot find `cargo`
2. Cannot find the path where the cargo definition is sourced from

So the whole talk about aliases and/or functions not expanding, etc. is obviously a dead end. Your issue is only about the second issue obscuring the first issue. If you cannot source the right environment file, you will of course not have the `cargo` function.

I would try `echo $PWD` and similar techniques a few more times and I am sure this is quite easily cracked.

**Comment by codeinabox** [comment]
Thank you, I got the mocking working in the end using `let $BASH_ENV = getcwd() . "/.vim_bash_env"`
