### ISSUE TITLE
Enhancement: use VimL's `v:errors` and/or new assert functions?

### ISSUE THREAD

**Issue by geoffharcourt** [junegunn/vader.vim#63]
This would not be backwards compatible, but might make future development of tests much easier. As of the 944-953 patches, VimL now has a `v:errors` variable and some new assertion functions.

Commit to Vim:
https://github.com/vim/vim/commit/43345546ae63710441f066648b8485fb545b3801

PR to integrate above change into Neovim:
https://github.com/neovim/neovim/pull/3857

I noticed while trying to write a test that verified that a keypress is supposed to `echoe` that I needed to do some try-catch maneuvering in order to not stop execution of the test runner. Not sure if these patches would help with that problem, but it seems like it could be convenient to piggyback off of standardized, upstream behavior when possible.

**Comment by junegunn** [comment]
Thanks for the suggestion. But currently I don't see any benefit of using those constructs, and unfortunately no, they don't help with the problem you described. I currently use Vader to test [vim-plug](https://github.com/junegunn/vim-plug) against [various versions of Vim](https://travis-ci.org/junegunn/vim-plug/jobs/98520022) - because I have to make sure that it works with older versions. Using these new features will only make it impossible.

**Comment by geoffharcourt** [comment]
Thanks for the feedback!

**Comment by junegunn** [comment]
Thanks for letting me know.
